### PR TITLE
Release v0.1.10

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/575)

### CODE REVIEW

**Comment by thierry-FreeBSD** [comment]
Compilation still aborts on FreeBSD:

```
/usr/local/libexec/ccache/cc  -I/usr/local/include -I/usr/local/include/opus -I/usr/local/include/opencv -O2 -pipe  -fstack-protector -fno-strict-aliasing -std=c99 -pedantic -Wall -Wextra -Weverything -Wno-cast-align -Wno-conversion -Wno-covered-switch-default -Wno-disabled-macro-expansion -Wno-documentation-deprecated-sync -Wno-format-nonliteral -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-padded -Wno-parentheses -Wno-return-type -Wno-sign-compare -Wno-sign-conversion -Wno-tautological-constant-out-of-range-compare -Wno-type-limits -Wno-undef -Wno-unreachable-code -Wno-unused-macros -Wno-unused-parameter -Wno-vla -Wno-assign-enum -Wno-bad-function-cast -Wno-double-promotion -Wno-gnu-zero-variadic-macro-arguments -Wno-packed -Wno-reserved-id-macro -Wno-shadow -Wno-shorten-64-to-32 -Wno-unreachable-code-return -Wno-used-but-marked-unused -isystem /usr/local/include -isystem /usr/local/include/opus -isystem /usr/local/include -isystem /usr/local/include -isystem /usr/local/include -isystem /usr/local/include -isystem /usr/local/include -isystem /usr/local/include -isystem /usr/local/include -O2 -pipe  -fstack-protector -fno-strict-aliasing -MD -MT CMakeFiles/toxcore-sut.dir/testing/hstox/driver.c.o -MF CMakeFiles/toxcore-sut.dir/testing/hstox/driver.c.o.d -o CMakeFiles/toxcore-sut.dir/testing/hstox/driver.c.o   -c testing/hstox/driver.c
testing/hstox/driver.c:229:24: error: variable has incomplete type 'struct sockaddr_in'
    struct sockaddr_in servaddr;
                       ^
testing/hstox/driver.c:229:12: note: forward declaration of 'struct sockaddr_in'
    struct sockaddr_in servaddr;
           ^
testing/hstox/driver.c:231:38: error: use of undeclared identifier 'INADDR_ANY'
    servaddr.sin_addr.s_addr = htons(INADDR_ANY);
                                     ^
testing/hstox/driver.c:231:38: error: use of undeclared identifier 'INADDR_ANY'
testing/hstox/driver.c:231:38: error: use of undeclared identifier 'INADDR_ANY'
testing/hstox/driver.c:231:38: error: use of undeclared identifier 'INADDR_ANY'
5 errors generated.
ninja: build stopped: subcommand failed.
*** Error code 1

```

**Comment by sudden6** [comment]
Builds fine on OpenSUSE Leap 42.3 and seems to work fine with qTox 1.11

**Comment by nurupo** [comment]
@thierry-FreeBSD it doesn't include the FreeBSD fixes from https://github.com/TokTok/c-toxcore/pull/505. Once those are included (in 0.1.11?), it should compile on FreeBSD successfully.

**Comment by nurupo** [comment]
@robinlinden don't forget to to do the thing (https://github.com/TokTok/c-toxcore/issues/569) after this is merged.

**Comment by robinlinden** [comment]
@nurupo No worries. I'll do the thing as soon as someone LGTMs this. Thanks
for the reminder tho.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/575#-:-KrgSMqMx4_MJAMI9Q5M:b-jbsf8z)*

**Comment by nurupo** [comment]
I thought you were waiting on @iphy specifically.

Looks good to me. Toxcore master builds on Jenkins and the static code analysis seems good, it gained [a couple false positives](https://build.tox.chat/job/libtoxcore-toktok_analyze_cppcheck/145/cppcheckResult/) but that's about it.

:lgtm_strong:

---

Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/c-toxcore/575#-:-KrgTbOaHIc1nVTGOqgi:b-r1mbh3)*
